"""notes table

Revision ID: a6cc41e568c1
Revises: 
Create Date: 2020-07-30 09:54:36.978515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6cc41e568c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_message'), 'note', ['message'], unique=False)
    op.create_index(op.f('ix_note_name'), 'note', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_name'), table_name='note')
    op.drop_index(op.f('ix_note_message'), table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
