"""note timestamps

Revision ID: b980090d93aa
Revises: a6cc41e568c1
Create Date: 2020-07-30 09:59:15.073736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b980090d93aa'
down_revision = 'a6cc41e568c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_note_timestamp'), 'note', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_timestamp'), table_name='note')
    op.drop_column('note', 'timestamp')
    # ### end Alembic commands ###
